const Config = {
  baseUrl: "https://niche.ink",
  methods: {
    getCategories: {
      description: "Get magic categories",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/new-cats",
      mustStringify: true,
      isFlatResponse: true,
    },
    getArticles: {
      description: "Get magic articles",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/magics",
      mustStringify: true,
      isFlatResponse: true,
    },
    getCredits: {
      description: "Get credits",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/credits",
      mustStringify: true,
      isFlatResponse: true,
    },
    getOneArticles: {
      description: "Get magic articles",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/magics/{item}",
      mustStringify: true,
      isFlatResponse: true,
    },
    getWriters: {
      description: "Get magic writers",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/rits",
      mustStringify: true,
      isFlatResponse: true,
    },
    getWritersArticles: {
      description: "get Writers Articles",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/magics?authors.id={item}",
      mustStringify: true,
      isFlatResponse: true,
    },
    getCategoryArticles: {
      description: "get Category Articles",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/magics?categories[].id={item}",
      mustStringify: true,
      isFlatResponse: true,
    },
    getCategoryArticlesHome: {
      description: "get Category Articles Home",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/magics?categories[].id={item}",
      mustStringify: true,
      isFlatResponse: true,
    },
    getFeatured: {
      description: "getFeatured",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/magics?featured=true",
      mustStringify: true,
      isFlatResponse: true,
    },
    registerUser: {
      description: "registerUser",
      isAuthenticated: false,
      verb: "POST",
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: "/auth/local/register",
      mustStringify: true,
      isFlatResponse: false,
    },
    updateUser: {
      description: "updateUser",
      isAuthenticated: true,
      verb: "PUT",
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: "/users/{id}",
      mustStringify: true,
      isFlatResponse: false,
    },
    makeOrder: {
      description: "make an order for one item",
      isAuthenticated: true,
      verb: "POST",
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: "/orders",
      mustStringify: true,
      isFlatResponse: false,
    },
    login: {
      description: "login",
      isAuthenticated: false,
      verb: "POST",
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: "/auth/local",
      mustStringify: true,
      isFlatResponse: false,
    },
    contactus: {
      description: "contactus",
      isAuthenticated: false,
      verb: "POST",
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: "/mymail",
      mustStringify: true,
      isFlatResponse: false,
    },
    beWriter: {
      description: "beWriter",
      isAuthenticated: false,
      verb: "POST",
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: "/mymail",
      mustStringify: true,
      isFlatResponse: false,
    },
    getArticleComments: {
      description: "get Article comments",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/comments?magics={item}",
      mustStringify: true,
      isFlatResponse: true,
    },
    createArticleComments: {
      description: "create Article comments",
      isAuthenticated: true,
      verb: "POST",
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: "/comments",
      mustStringify: true,
      isFlatResponse: false,
    },
    deleteComment: {
      description: "delete Article comment by id",
      isAuthenticated: true,
      verb: "DELETE",
      sendDeviceKey: false,
      jsonMethod: true,
      suffixUrl: "/comments/{id}",
      mustStringify: true,
      isFlatResponse: false,
    },
    getProductCategories: {
      description: "get product categories",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/ecom-categories",
      mustStringify: true,
      isFlatResponse: true,
    },
    getProducts: {
      description: "get products",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/ecom-products",
      mustStringify: true,
      isFlatResponse: true,
    },
    getCategoryProducts: {
      description: "get Category Product",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/ecom-products?ecom_category[].id={item}",
      mustStringify: true,
      isFlatResponse: true,
    },
    getOneProduct: {
      description: "get one products",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/ecom-products/{id}",
      mustStringify: true,
      isFlatResponse: true,
    },
    getWriter: {
      description: "get one writer",
      isAuthenticated: false,
      verb: "GET",
      sendDeviceKey: false,
      jsonMethod: false,
      suffixUrl: "/rits/{id}",
      mustStringify: true,
      isFlatResponse: true,
    },

    //https://niche.ink///
  },
};

export default Config;
